DROP TABLE T_TESTE_SEQUENCE;

--GENERATED ALWAYS AS IDENTITY
CREATE TABLE T_TESTE_SEQUENCE
(
 CD_TESTE_SQ NUMBER(3),
 NM_TESTE_SQ VARCHAR2(30)
);

ALTER TABLE T_TESTE_SEQUENCE
    ADD CONSTRAINT PK_TESTE_SEQUENCE PRIMARY KEY (CD_TESTE_SQ);
    
DROP SEQUENCE SQ_TESTE_SEQUENCE;
    
CREATE SEQUENCE SQ_TESTE_SEQUENCE
START WITH 1
INCREMENT BY 1
MAXVALUE 999
NOCACHE
NOCYCLE;

ALTER SEQUENCE SQ_TESTE_SEQUENCE
MAXVALUE 855;



SELECT * FROM USER_SEQUENCES where SEQUENCE_NAME = 'SQ_TESTE_SEQUENCE';


DELETE FROM T_TESTE_SEQUENCE;


DECLARE
  i NUMBER;
BEGIN
  FOR i IN 1..10 LOOP
        INSERT INTO T_TESTE_SEQUENCE 
            VALUES (SQ_TESTE_SEQUENCE.NEXTVAL, 'Item ' || TO_CHAR(SQ_TESTE_SEQUENCE.NEXTVAL));
  END LOOP;
  COMMIT;
END;

SELECT * FROM T_TESTE_SEQUENCE ORDER BY CD_TESTE_SQ ASC;