CREATE SEQUENCE seq_cliente
START WITH 1
INCREMENT BY 1
MAXVALUE 1000
MINVALUE 1
NOCACHE
CYCLE;

DROP SEQUENCE seq_cliente
----------------
CREATE TABLE cliente (
id NUMBER,
nome VARCHAR2(100),
CONSTRAINT pk_cliente PRIMARY KEY(id)
);

CREATE TABLE cliente2 (
id NUMBER GENERATED ALWAYS AS IDENTITY,
nome VARCHAR2(100),
CONSTRAINT pk_cliente2 PRIMARY KEY(id)
);

DROP TABLE cliente

CREATE OR REPLACE TRIGGER trg_cliente
BEFORE INSERT ON cliente
FOR EACH ROW
    BEGIN
        :NEW.id := seq_cliente.NEXTVAL;
    END;
    
INSERT INTO cliente2 (nome) VALUES ('Teste');

SELECT * FROM cliente2;

DELETE FROM cliente;
DELETE FROM cliente2;
